import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  DM_Sans,
  Playfair_Display,
  Noto_Sans_Bengali,
} from "next/font/google";
import "./globals.css";
import QueryProvider from "./tanstack/provider/TanstackQueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
});

const notoSansBengali = Noto_Sans_Bengali({
  variable: "--font-noto-sans-bengali",
  subsets: ["bengali"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${dmSans.variable} ${playfairDisplay.variable} ${notoSansBengali.variable} antialiased`}
        suppressHydrationWarning
      >
        {/* Wrap children in client-side QueryProvider */}
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
